# Generated by Django 6.1 on 2026-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('urls', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField()),
                ('attachment', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
