# Generated by Django 6.1 on 2026-08-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_email_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attachment',
        ),
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.JSONField(default=list),
        ),
    ]
