def format_risk_email(data):

    threat = data["threat_intelligence"]

    url_rows = ""

    for result in threat["url_results"]:
        url_rows += f"""
        <tr>
            <td>{result["url"]}</td>
            <td>{result["malicious"]}</td>
            <td>{result["suspicious"]}</td>
            <td>{result["harmless"]}</td>
            <td>{result["undetected"]}</td>
        </tr>
        """

    html = f"""
    <!DOCTYPE html>
    <html>
    <body style="font-family: Arial, sans-serif;">

        <h2>Security Risk Analysis Report</h2>

        <p>
            <strong>Email ID:</strong>
            {data["email_id"]}
        </p>

        <p>
            <strong>Risk Score:</strong>
            {data["risk_score"]}/100
        </p>

        <p>
            <strong>Classification:</strong>
            {data["classification"]}
        </p>

        <h3>Threat Intelligence</h3>

        <table border="1" cellpadding="8" cellspacing="0">
            <tr>
                <th>Metric</th>
                <th>Count</th>
            </tr>

            <tr>
                <td>Total URLs</td>
                <td>{threat["total_urls"]}</td>
            </tr>

            <tr>
                <td>Malicious</td>
                <td>{threat["malicious_count"]}</td>
            </tr>

            <tr>
                <td>Suspicious</td>
                <td>{threat["suspicious_count"]}</td>
            </tr>

            <tr>
                <td>Harmless</td>
                <td>{threat["harmless_count"]}</td>
            </tr>

            <tr>
                <td>Undetected</td>
                <td>{threat["undetected_count"]}</td>
            </tr>
        </table>

        <h3>URL Analysis</h3>

        <table border="1" cellpadding="8" cellspacing="0">

            <tr>
                <th>URL</th>
                <th>Malicious</th>
                <th>Suspicious</th>
                <th>Harmless</th>
                <th>Undetected</th>
            </tr>

            {url_rows}

        </table>

        <h3>Final Classification</h3>

        <p>
            <strong>{data["classification"]}</strong>
        </p>

        <p>
            This report was automatically generated by the
            Security Risk Engine.
        </p>

    </body>
    </html>
    """

    return html